# Document tagging

*This notebook first appeared as a [blog post](//betatim.github.io/posts/bumping) on [Tim Head](//betatim.github.io)'s blog.*

*License: [MIT](http://opensource.org/licenses/MIT)*

*(C) 2016, Tim Head.*
*Feel free to use, distribute, and modify with the above attribution.*

In [2]:
%config InlineBackend.figure_format='retina'
%matplotlib inline

In [3]:
import numpy as np
np.random.seed(3)
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_mldata
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.cross_validation import train_test_split

In [4]:
yeast = fetch_mldata('yeast')
X = yeast.data
y = yeast.target.T.toarray()
print(X.shape, y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

(2417, 103) (2417, 14)


In [5]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [15]:
et = ExtraTreesClassifier()
et.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [16]:
rf.score(X_test, y_test)

0.13498622589531681

In [17]:
et.score(X_test, y_test)

0.11570247933884298

In [61]:
print(et.predict_proba(X_test[:2,:])[0])
print(y_test[:2])
y_pred = et.predict(X_test)
average_precision_score(y_test, y_pred)

[[ 0.8  0.2]
 [ 1.   0. ]]
[[ 0.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  1.  1.  0.]]


0.58034117994014822

In [27]:
from sklearn.metrics import average_precision_score

In [36]:
y = np.array([[1, 0, 0], [0, 1, 1], [0, 0, 0]])
y_ = np.array([[1, 1, 0], [0, 1, 1], [0, 1, 0]])

average_precision_score(y, y_)

0.88888888888888884

In [22]:
from sklearn.datasets import fetch_20newsgroups
categories = [
        'alt.atheism',
        'talk.religion.misc',
        'comp.graphics',
        'sci.space',
    ]

data_test = fetch_20newsgroups(subset='test', categories=categories,
                               shuffle=True, random_state=42,)

In [25]:
data_test.target[:10]

array([2, 1, 1, 1, 1, 1, 2, 2, 0, 2])

In [60]:
fetch_mldata("wine quality").data.shape

HTTPError: HTTP Error 404: Dataset 'wine-quality' not found on mldata.org.